version: '2'

services:
    pictureminer-ml:
        build:
            context: ./pictureminer.ml-dev
        ports:
            - "9000:9000"
    
    pictureminer-backend:
        build:
            context: ./pictureminer.api-dev
        ports:
            - "8000:8000"

    pictureminer-frontend:
        build:
            context: ./pictureminer.web-dev
        ports:
            - "3000:3000"